version: '3.8'

services:
  # Frontend React application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mis-student-verification-app
    network_mode: "host"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - PORT=3797
      - REACT_APP_API_URL=http://localhost:3798/api
    restart: unless-stopped
    depends_on:
      - backend

  # Node.js Backend server
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mis-student-verification-backend
    network_mode: "host"
    volumes:
      - ./server:/app
      - ./server/uploads:/app/uploads
      - ./server/outputs:/app/outputs
      - ./server/logs:/app/logs
    environment:
      - NODE_ENV=development
      - PORT=3798
      - LLM_ENDPOINT=ollama
      - OLLAMA_URL=http://localhost:11434/api/generate
      - OLLAMA_MODEL=mistral:latest
      - OLLAMA_EMBED_MODEL=nomic-embed-text
      - MONGODB_URI=mongodb://localhost:3799/mis-verification
    restart: unless-stopped
    depends_on:
      - mongodb

  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: mis-student-verification-mongodb
    network_mode: "host"
    command: mongod --port 3799
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: