version: '3.8'

services:
  # Frontend React application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mis-student-verification-app
    network_mode: host
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - PORT=3797
      - REACT_APP_API_URL=http://localhost:3798/api
    restart: unless-stopped
    depends_on:
      - backend

  # Python Flask Backend server
  backend:
    build:
      context: ./python_backend
      dockerfile: Dockerfile
    container_name: mis-student-verification-backend
    network_mode: host
    volumes:
      - ./python_backend:/app
      - ./python_backend/uploads:/app/uploads
      - ./python_backend/outputs:/app/outputs
      - ./python_backend/data:/app/data
      - ./python_backend/vector_db:/app/vector_db
    environment:
      - FLASK_ENV=development
      - PORT=3798
      - LLM_ENDPOINT=ollama
      - OLLAMA_URL=http://localhost:11434/api/generate
      - OLLAMA_MODEL=phi:mini
      - OLLAMA_ALTERNATIVE_MODEL=mistral:latest
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=3799
      - POSTGRES_DB=mis_verification
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    depends_on:
      - postgres

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: mis-student-verification-postgres
    network_mode: host
    environment:
      - POSTGRES_DB=mis_verification
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: